// Generato da phonenumbers + CLDR (nomi in italiano). Non modificare a mano.

class Country {
  const Country(this.iso, this.name, this.dial);
  final String iso; // ISO 3166-1 alfa-2
  final String name;
  final String dial; // es. '+39'
}

const kCountries = <Country>[
  Country('AF', 'Afghanistan', '+93'),
  Country('AL', 'Albania', '+355'),
  Country('DZ', 'Algeria', '+213'),
  Country('AD', 'Andorra', '+376'),
  Country('AO', 'Angola', '+244'),
  Country('AI', 'Anguilla', '+1'),
  Country('AG', 'Antigua e Barbuda', '+1'),
  Country('SA', 'Arabia Saudita', '+966'),
  Country('AR', 'Argentina', '+54'),
  Country('AM', 'Armenia', '+374'),
  Country('AW', 'Aruba', '+297'),
  Country('AU', 'Australia', '+61'),
  Country('AT', 'Austria', '+43'),
  Country('AZ', 'Azerbaigian', '+994'),
  Country('BS', 'Bahamas', '+1'),
  Country('BH', 'Bahrein', '+973'),
  Country('BD', 'Bangladesh', '+880'),
  Country('BB', 'Barbados', '+1'),
  Country('BE', 'Belgio', '+32'),
  Country('BZ', 'Belize', '+501'),
  Country('BJ', 'Benin', '+229'),
  Country('BM', 'Bermuda', '+1'),
  Country('BT', 'Bhutan', '+975'),
  Country('BY', 'Bielorussia', '+375'),
  Country('BO', 'Bolivia', '+591'),
  Country('BA', 'Bosnia ed Erzegovina', '+387'),
  Country('BW', 'Botswana', '+267'),
  Country('BR', 'Brasile', '+55'),
  Country('BN', 'Brunei', '+673'),
  Country('BG', 'Bulgaria', '+359'),
  Country('BF', 'Burkina Faso', '+226'),
  Country('BI', 'Burundi', '+257'),
  Country('KH', 'Cambogia', '+855'),
  Country('CM', 'Camerun', '+237'),
  Country('CA', 'Canada', '+1'),
  Country('CV', 'Capo Verde', '+238'),
  Country('BQ', 'Caraibi Olandesi', '+599'),
  Country('CZ', 'Cechia', '+420'),
  Country('TD', 'Ciad', '+235'),
  Country('CL', 'Cile', '+56'),
  Country('CN', 'Cina', '+86'),
  Country('CY', 'Cipro', '+357'),
  Country('VA', 'Città del Vaticano', '+39'),
  Country('CO', 'Colombia', '+57'),
  Country('KM', 'Comore', '+269'),
  Country('CD', 'Congo - Kinshasa', '+243'),
  Country('CG', 'Congo-Brazzaville', '+242'),
  Country('KP', 'Corea del Nord', '+850'),
  Country('KR', 'Corea del Sud', '+82'),
  Country('CI', 'Costa d’Avorio', '+225'),
  Country('CR', 'Costa Rica', '+506'),
  Country('HR', 'Croazia', '+385'),
  Country('CU', 'Cuba', '+53'),
  Country('CW', 'Curaçao', '+599'),
  Country('DK', 'Danimarca', '+45'),
  Country('DM', 'Dominica', '+1'),
  Country('EC', 'Ecuador', '+593'),
  Country('EG', 'Egitto', '+20'),
  Country('SV', 'El Salvador', '+503'),
  Country('AE', 'Emirati Arabi Uniti', '+971'),
  Country('ER', 'Eritrea', '+291'),
  Country('EE', 'Estonia', '+372'),
  Country('SZ', 'Eswatini', '+268'),
  Country('ET', 'Etiopia', '+251'),
  Country('FJ', 'Figi', '+679'),
  Country('PH', 'Filippine', '+63'),
  Country('FI', 'Finlandia', '+358'),
  Country('FR', 'Francia', '+33'),
  Country('GA', 'Gabon', '+241'),
  Country('GM', 'Gambia', '+220'),
  Country('GE', 'Georgia', '+995'),
  Country('DE', 'Germania', '+49'),
  Country('GH', 'Ghana', '+233'),
  Country('JM', 'Giamaica', '+1'),
  Country('JP', 'Giappone', '+81'),
  Country('GI', 'Gibilterra', '+350'),
  Country('DJ', 'Gibuti', '+253'),
  Country('JO', 'Giordania', '+962'),
  Country('GR', 'Grecia', '+30'),
  Country('GD', 'Grenada', '+1'),
  Country('GL', 'Groenlandia', '+299'),
  Country('GP', 'Guadalupa', '+590'),
  Country('GU', 'Guam', '+1'),
  Country('GT', 'Guatemala', '+502'),
  Country('GG', 'Guernsey', '+44'),
  Country('GN', 'Guinea', '+224'),
  Country('GQ', 'Guinea Equatoriale', '+240'),
  Country('GW', 'Guinea-Bissau', '+245'),
  Country('GY', 'Guyana', '+592'),
  Country('GF', 'Guyana Francese', '+594'),
  Country('HT', 'Haiti', '+509'),
  Country('HN', 'Honduras', '+504'),
  Country('IN', 'India', '+91'),
  Country('ID', 'Indonesia', '+62'),
  Country('IR', 'Iran', '+98'),
  Country('IQ', 'Iraq', '+964'),
  Country('IE', 'Irlanda', '+353'),
  Country('IS', 'Islanda', '+354'),
  Country('AC', 'Isola Ascensione', '+247'),
  Country('CX', 'Isola Christmas', '+61'),
  Country('IM', 'Isola di Man', '+44'),
  Country('NF', 'Isola Norfolk', '+672'),
  Country('AX', 'Isole Åland', '+358'),
  Country('KY', 'Isole Cayman', '+1'),
  Country('CC', 'Isole Cocos (Keeling)', '+61'),
  Country('CK', 'Isole Cook', '+682'),
  Country('FK', 'Isole Falkland', '+500'),
  Country('FO', 'Isole Fær Øer', '+298'),
  Country('MP', 'Isole Marianne Settentrionali', '+1'),
  Country('MH', 'Isole Marshall', '+692'),
  Country('SB', 'Isole Salomone', '+677'),
  Country('TC', 'Isole Turks e Caicos', '+1'),
  Country('VI', 'Isole Vergini Americane', '+1'),
  Country('VG', 'Isole Vergini Britanniche', '+1'),
  Country('IL', 'Israele', '+972'),
  Country('IT', 'Italia', '+39'),
  Country('JE', 'Jersey', '+44'),
  Country('KZ', 'Kazakistan', '+7'),
  Country('KE', 'Kenya', '+254'),
  Country('KG', 'Kirghizistan', '+996'),
  Country('KI', 'Kiribati', '+686'),
  Country('XK', 'Kosovo', '+383'),
  Country('KW', 'Kuwait', '+965'),
  Country('LA', 'Laos', '+856'),
  Country('LS', 'Lesotho', '+266'),
  Country('LV', 'Lettonia', '+371'),
  Country('LB', 'Libano', '+961'),
  Country('LR', 'Liberia', '+231'),
  Country('LY', 'Libia', '+218'),
  Country('LI', 'Liechtenstein', '+423'),
  Country('LT', 'Lituania', '+370'),
  Country('LU', 'Lussemburgo', '+352'),
  Country('MK', 'Macedonia del Nord', '+389'),
  Country('MG', 'Madagascar', '+261'),
  Country('MW', 'Malawi', '+265'),
  Country('MY', 'Malaysia', '+60'),
  Country('MV', 'Maldive', '+960'),
  Country('ML', 'Mali', '+223'),
  Country('MT', 'Malta', '+356'),
  Country('MA', 'Marocco', '+212'),
  Country('MQ', 'Martinica', '+596'),
  Country('MR', 'Mauritania', '+222'),
  Country('MU', 'Mauritius', '+230'),
  Country('YT', 'Mayotte', '+262'),
  Country('MX', 'Messico', '+52'),
  Country('FM', 'Micronesia', '+691'),
  Country('MD', 'Moldavia', '+373'),
  Country('MC', 'Monaco', '+377'),
  Country('MN', 'Mongolia', '+976'),
  Country('ME', 'Montenegro', '+382'),
  Country('MS', 'Montserrat', '+1'),
  Country('MZ', 'Mozambico', '+258'),
  Country('MM', 'Myanmar (Birmania)', '+95'),
  Country('NA', 'Namibia', '+264'),
  Country('NR', 'Nauru', '+674'),
  Country('NP', 'Nepal', '+977'),
  Country('NI', 'Nicaragua', '+505'),
  Country('NE', 'Niger', '+227'),
  Country('NG', 'Nigeria', '+234'),
  Country('NU', 'Niue', '+683'),
  Country('NO', 'Norvegia', '+47'),
  Country('NC', 'Nuova Caledonia', '+687'),
  Country('NZ', 'Nuova Zelanda', '+64'),
  Country('OM', 'Oman', '+968'),
  Country('NL', 'Paesi Bassi', '+31'),
  Country('PK', 'Pakistan', '+92'),
  Country('PW', 'Palau', '+680'),
  Country('PA', 'Panama', '+507'),
  Country('PG', 'Papua Nuova Guinea', '+675'),
  Country('PY', 'Paraguay', '+595'),
  Country('PE', 'Perù', '+51'),
  Country('PF', 'Polinesia Francese', '+689'),
  Country('PL', 'Polonia', '+48'),
  Country('PT', 'Portogallo', '+351'),
  Country('PR', 'Portorico', '+1'),
  Country('QA', 'Qatar', '+974'),
  Country('HK', 'RAS di Hong Kong', '+852'),
  Country('MO', 'RAS di Macao', '+853'),
  Country('GB', 'Regno Unito', '+44'),
  Country('CF', 'Repubblica Centrafricana', '+236'),
  Country('DO', 'Repubblica Dominicana', '+1'),
  Country('RE', 'Riunione', '+262'),
  Country('RO', 'Romania', '+40'),
  Country('RW', 'Ruanda', '+250'),
  Country('RU', 'Russia', '+7'),
  Country('EH', 'Sahara Occidentale', '+212'),
  Country('KN', 'Saint Kitts e Nevis', '+1'),
  Country('LC', 'Saint Lucia', '+1'),
  Country('MF', 'Saint Martin', '+590'),
  Country('VC', 'Saint Vincent e Grenadine', '+1'),
  Country('BL', 'Saint-Barthélemy', '+590'),
  Country('PM', 'Saint-Pierre e Miquelon', '+508'),
  Country('WS', 'Samoa', '+685'),
  Country('AS', 'Samoa Americane', '+1'),
  Country('SM', 'San Marino', '+378'),
  Country('SH', 'Sant’Elena', '+290'),
  Country('ST', 'São Tomé e Príncipe', '+239'),
  Country('SN', 'Senegal', '+221'),
  Country('RS', 'Serbia', '+381'),
  Country('SC', 'Seychelles', '+248'),
  Country('SL', 'Sierra Leone', '+232'),
  Country('SG', 'Singapore', '+65'),
  Country('SX', 'Sint Maarten', '+1'),
  Country('SY', 'Siria', '+963'),
  Country('SK', 'Slovacchia', '+421'),
  Country('SI', 'Slovenia', '+386'),
  Country('SO', 'Somalia', '+252'),
  Country('ES', 'Spagna', '+34'),
  Country('LK', 'Sri Lanka', '+94'),
  Country('US', 'Stati Uniti', '+1'),
  Country('SS', 'Sud Sudan', '+211'),
  Country('ZA', 'Sudafrica', '+27'),
  Country('SD', 'Sudan', '+249'),
  Country('SR', 'Suriname', '+597'),
  Country('SJ', 'Svalbard e Jan Mayen', '+47'),
  Country('SE', 'Svezia', '+46'),
  Country('CH', 'Svizzera', '+41'),
  Country('TJ', 'Tagikistan', '+992'),
  Country('TW', 'Taiwan', '+886'),
  Country('TZ', 'Tanzania', '+255'),
  Country('PS', 'Territori Palestinesi', '+970'),
  Country('IO', 'Territorio Britannico dell’Oceano Indiano', '+246'),
  Country('TH', 'Thailandia', '+66'),
  Country('TL', 'Timor Est', '+670'),
  Country('TG', 'Togo', '+228'),
  Country('TK', 'Tokelau', '+690'),
  Country('TO', 'Tonga', '+676'),
  Country('TT', 'Trinidad e Tobago', '+1'),
  Country('TA', 'Tristan da Cunha', '+290'),
  Country('TN', 'Tunisia', '+216'),
  Country('TR', 'Turchia', '+90'),
  Country('TM', 'Turkmenistan', '+993'),
  Country('TV', 'Tuvalu', '+688'),
  Country('UA', 'Ucraina', '+380'),
  Country('UG', 'Uganda', '+256'),
  Country('HU', 'Ungheria', '+36'),
  Country('UY', 'Uruguay', '+598'),
  Country('UZ', 'Uzbekistan', '+998'),
  Country('VU', 'Vanuatu', '+678'),
  Country('VE', 'Venezuela', '+58'),
  Country('VN', 'Vietnam', '+84'),
  Country('WF', 'Wallis e Futuna', '+681'),
  Country('YE', 'Yemen', '+967'),
  Country('ZM', 'Zambia', '+260'),
  Country('ZW', 'Zimbabwe', '+263'),
];

Country? countryFor(String iso) => kCountries.where((c) => c.iso == iso).firstOrNull;
